version: '3.1'

services:
  # The DB service
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: xiuser
      MYSQL_PASSWORD: xipassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xidb
    networks:
      - lsb
    # Run all the .sql files in the /sql directory to initalize the DB. This only hapens the first time this service is started and will not handle additions/modifications
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /media/dream/lsb-database:/var/lib/mysql
    ports:
      - "3306:3306"

  # The server service
  ffxi_server_main:
    # Build whatever is in the Dockerfile in the server root folder
    build: .
    image: ffxi_server
    environment:
      XI_BINARY_DIR: /lsb-build
      PYTHONUNBUFFERED: 1
      XI_NETWORK_MAP_HOST: 172.23.66.53
#    command: > 
#      /bin/bash -c 'cmake -S/lsb-src -B/lsb-build && cd /lsb-build && make -j 8 && python3 ./tools/docker/launch_lobby.py'
    command: /bin/bash -c 'python3 ./tools/docker/launch_main.py'
    depends_on:
      - db
      - traefik
      - broker
    networks:
      - lsb
    labels:
      - "traefik.enable=true"

      - "traefik.udp.routers.map1udp.service=svc_map1udp"
      - "traefik.udp.services.svc_map1udp.loadbalancer.server.port=22222"

      - "traefik.tcp.routers.connect1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.connect1.entrypoints=connect1"
      - "traefik.tcp.routers.connect1.service=svc_connect1"
      - "traefik.tcp.services.svc_connect1.loadbalancer.server.port=54230"

      - "traefik.tcp.routers.connect2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.connect2.entrypoints=connect2"
      - "traefik.tcp.routers.connect2.service=svc_connect2"
      - "traefik.tcp.services.svc_connect2.loadbalancer.server.port=54231"

      - "traefik.tcp.routers.connect3.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.connect3.entrypoints=connect3"
      - "traefik.tcp.routers.connect3.service=svc_connect3"
      - "traefik.tcp.services.svc_connect3.loadbalancer.server.port=54001"

      - "traefik.tcp.routers.search.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.search.entrypoints=search"
      - "traefik.tcp.routers.search.service=svc_search"
      - "traefik.tcp.services.svc_search.loadbalancer.server.port=54002"
    volumes:
      - /media/dream/lsb-build:/lsb-build

  ffxi_server_map1:
    depends_on:
      - ffxi_server_main
    image: ffxi_server
    environment:
      XI_BINARY_DIR: /lsb-build
      PYTHONUNBUFFERED: 1
      XI_NETWORK_MAP_HOST: 172.23.66.53
      XI_NETWORK_MAP_PORT: 22222
    command: >
      /bin/bash -c 'dockerize --wait tcp://ffxi_server_main:54001 --timeout 2h -wait-retry-interval 20s && python3 ./tools/docker/launch_map.py'
    networks:
      - lsb
    labels:
      - "traefik.enable=true"

      - "traefik.udp.routers.map1udp.service=svc_map1udp"
      - "traefik.udp.services.svc_map1udp.loadbalancer.server.port=22222"
    volumes:
      - /media/dream/lsb-build:/lsb-build
    profiles:
      - donotstart

  traefik:
    image: traefik
    restart: unless-stopped
    environment:
      TRAEFIK_API_DASHBOARD: false
      TRAEFIK_API_INSECURE: true

      TRAEFIK_ENTRYPOINTS_MAP1UDP: true
      TRAEFIK_ENTRYPOINTS_MAP1UDP_ADDRESS: ":22222/udp"
      TRAEFIK_ENTRYPOINTS_CONNECT1: true
      TRAEFIK_ENTRYPOINTS_CONNECT1_ADDRESS: ":54230/tcp"
      TRAEFIK_ENTRYPOINTS_CONNECT2: true
      TRAEFIK_ENTRYPOINTS_CONNECT2_ADDRESS: ":54231/tcp"
      TRAEFIK_ENTRYPOINTS_CONNECT3: true
      TRAEFIK_ENTRYPOINTS_CONNECT3_ADDRESS: ":54001/tcp"
      TRAEFIK_ENTRYPOINTS_SEARCH: true
      TRAEFIK_ENTRYPOINTS_SEARCH_ADDRESS: ":54002/tcp"

      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_WATCH: true
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: "web"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false

    ports:
      - "54231:54231/tcp"
      - "54230:54230/tcp"
      - "54230:54230/udp"
      - "54001:54001/tcp"
      - "54002:54002/tcp"
      - "22222:22222/tcp"
      - "22222:22222/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
      - lsb

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - lsb
    logging:
      driver: "none"

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.23.66.53:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "packets-in:1:2,packets-out:1:2"
      LOG4J_LOGGER_KAFKA: WARN
    networks:
      - lsb
    logging:
      driver: "none"

networks:
  lsb:
    external: false
  web:
    external: true
